Repository silverstripe/silverstripe-versioned-admin, pull requests merged in 2018-10, with the labels that each got.

#66 MINOR Upgrade Bootstrap to 4.1.2
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#58 FIX Text collector translations now compile without errors
  lang/en.yml
  src/Extensions/BlockArchiveExtension.php
  src/Extensions/FileArchiveExtension.php
  src/Extensions/SiteTreeArchiveExtension.php
Labels: affects/v4, change/patch

#68 Archive add missing tab logic, fix file list
  src/ArchiveAdmin.php
  src/Extensions/FileArchiveExtension.php
Labels: affects/v4, change/patch

#70 Add Interfaces namespace for ArchiveViewProvider
  src/ArchiveAdmin.php
  src/Extensions/BlockArchiveExtension.php
  src/Extensions/FileArchiveExtension.php
  src/Extensions/SiteTreeArchiveExtension.php
  src/Interfaces/ArchiveViewProvider.php
  tests/ArchiveAdminTest/ViewProviderVersionedObject.php
Labels: affects/v4, change/major

#64 FIX Versioned-admin now declares its dependency on silverstripe-graphql
  composer.json
  package.json
  yarn.lock
Labels: affects/v4, change/patch
