Repository silverstripe/silverstripe-versioned-admin, pull requests merged in 2018-08, with the labels that each got.

#33 Show comparisons between versions in history viewer
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/HistoryViewer/HistoryViewer.js
  client/src/components/HistoryViewer/HistoryViewer.scss
  client/src/components/HistoryViewer/HistoryViewerCompareWarning.js
  client/src/components/HistoryViewer/HistoryViewerCompareWarning.scss
  client/src/components/HistoryViewer/HistoryViewerHeading.js
  client/src/components/HistoryViewer/HistoryViewerHeading.scss
  client/src/components/HistoryViewer/HistoryViewerToolbar.js
  client/src/components/HistoryViewer/HistoryViewerVersion.js
  client/src/components/HistoryViewer/HistoryViewerVersionDetail.js
  client/src/components/HistoryViewer/HistoryViewerVersionList.js
  client/src/components/HistoryViewer/HistoryViewerVersionList.scss
  client/src/components/HistoryViewer/HistoryViewerVersionState.js
  client/src/components/HistoryViewer/tests/HistoryViewer-test.js
  client/src/components/HistoryViewer/tests/HistoryViewerHeading-test.js
  client/src/components/HistoryViewer/tests/HistoryViewerToolbar-test.js
  client/src/components/HistoryViewer/tests/HistoryViewerVersion-test.js
  client/src/components/HistoryViewer/tests/HistoryViewerVersionList-test.js
  client/src/containers/HistoryViewer/HistoryViewerConfig.js
  client/src/legacy/HistoryViewer/HistoryViewerEntwine.js
  client/src/state/historyviewer/HistoryViewerActionTypes.js
  client/src/state/historyviewer/HistoryViewerActions.js
  client/src/state/historyviewer/HistoryViewerReducer.js
  client/src/state/historyviewer/tests/HistoryViewerReducer-test.js
  client/src/styles/bundle.scss
  client/src/types/compareType.js
  package.json
  src/Controllers/CMSPageHistoryViewerController.php
  src/Controllers/HistoryViewerController.php
  src/Forms/DiffField.php
  src/Forms/DiffTransformation.php
  templates/SilverStripe/VersionedAdmin/Forms/HistoryViewerField.ss
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/compare-mode.feature
  tests/Controllers/HistoryViewerControllerTest.php
  tests/Forms/DiffTransformationTest.php
  yarn.lock
Labels: affects/v4, change/minor, impact/high, type/enhancement

#43 FIX Reduce size of border radius on compare mode notice close button
  client/dist/styles/bundle.css
  client/src/components/HistoryViewer/HistoryViewerCompareWarning.scss
Labels: affects/v4, change/patch

#44 FIX Don't indicate pointer cursor when hovering a selected version in the list
  client/dist/styles/bundle.css
  client/src/components/HistoryViewer/HistoryViewerVersion.scss
  client/src/styles/bundle.scss
Labels: affects/v4, change/patch

#45 FIX When exiting compare mode, the version shown is the last selected version to compare from
  client/dist/js/bundle.js
  client/src/state/historyviewer/HistoryViewerReducer.js
  client/src/state/historyviewer/tests/HistoryViewerReducer-test.js
Labels: affects/v4, change/patch

#46 Add 'already selected' message for version chosen in compare mode
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/HistoryViewer/HistoryViewer.js
  client/src/components/HistoryViewer/HistoryViewerVersion.js
  client/src/components/HistoryViewer/HistoryViewerVersion.scss
Labels: affects/v4, change/minor

#48 Center alert message and conditionally show close button/selected mes…
  client/dist/styles/bundle.css
  client/src/components/HistoryViewer/HistoryViewerCompareWarning.scss
  client/src/components/HistoryViewer/HistoryViewerVersion.scss
Labels: affects/v4, change/patch

#50 FIX Disable compare mode when there is only one version available
  client/dist/js/bundle.js
  client/src/components/HistoryViewer/HistoryViewer.js
  client/src/components/HistoryViewer/HistoryViewerHeading.js
  client/src/components/HistoryViewer/HistoryViewerVersion.js
  client/src/components/HistoryViewer/HistoryViewerVersionDetail.js
  client/src/components/HistoryViewer/HistoryViewerVersionList.js
  client/src/components/HistoryViewer/tests/HistoryViewer-test.js
Labels: affects/v4, change/patch

#52 FIX Use get_one_by_stage when fetching SiteTree for a specific stage
  src/Controllers/HistoryControllerFactory.php
  tests/Controllers/HistoryControllerFactoryTest.php
  tests/Controllers/HistoryControllerFactoryTest.yml
  tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php
Labels: affects/v4, change/patch

#53 FIX Check ID is numeric before using it
  src/Controllers/HistoryControllerFactory.php
Labels: affects/v4, change/patch

#42 FIX Label RestoreAction clearer as 'Restore *to* draft'
  src/Extensions/ArchiveRestoreAction.php
Labels: affects/v4, change/patch

#55 NEW HistoryViewerField now uses schemaData to inject necessary input props
  client/dist/js/bundle.js
  client/src/components/HistoryViewer/HistoryViewerVersionList.js
  client/src/legacy/HistoryViewer/HistoryViewerEntwine.js
  src/Forms/HistoryViewerField.php
  templates/SilverStripe/VersionedAdmin/Forms/HistoryViewerField.ss
Labels: affects/v4, change/minor
